### ISSUE TITLE
Working with Husky

### ISSUE THREAD

**Issue by ctobolski** [chiptopher/guet#25] opened 2019-12-17 16:49 UTC
#### Actual behavior?
Installing Guet is incompatible with another dependency that also modifies your git hooks

#### Expected behavior?
Guet plays nicely with husky

**Comment by chiptopher** [comment] 2020-01-12 21:11
I've not used husky much, but I played I around with it this morning. This was the configuration I ended up getting to work as intended.

```
  "husky": {
    "hooks": {
      "pre-commit": "yarn test && .git/hooks/pre-commit-guet",
      "commit-msg": "yarn test && .git/hooks/commit-msg-guet",
      "post-commit": "yarn test && .git/hooks/post-commit-guet"
    }
  }
```

To get the `-guet` git hooks, as of 2.2.0, you can do `guet start -a`. Otherwise, `guet start` will prompt you to create them.

**Comment by PvtRadio** [comment] 2020-01-15 15:32
When husky is used in a subproject(we have a mono repo) Guet cant find the location of the commit message, and is not appending the committers correctly

**Comment by ctobolski** [comment] 2020-01-15 18:09
The husky docs recommend against installing husky in a sub folder of a mono repo. I plan on looking at this more this weekend

**Comment by chiptopher** [comment] 2020-03-09 10:58
So I looked into this further, and before using the `"commit-msg": ".git/hooks/commit-msg-guet"` trick would call the script, but the script wouldn't do anything. The problem should be addressed now, so I'm going to close the issue for the time being.

**Closed by chiptopher** 2020-03-09 10:58 UTC

**Comment by chiptopher** [comment] 2020-06-06 14:12
I also added using husky to the FAQ in #87
